title: BoluDOS Operating System
description: A CC OS for people who hate themselves
theme: just-the-docs

search_enabled: true

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

url: https://piguman3.github.io/boludos

